server:
  port: 8080

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   # keep messages schema-agnostic

app:
  kafka:
    topic:
      orders: orders.topic
  api-key: "38f1b725-fa63-484d-a904-0551321ae2f5"
  

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.orderservice: DEBUG
    org.apache.kafka: WARN
